# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e70a35922e13a0a88b26e8f4db8874eb13bf6531130337bb0e237c44b079f93c832eafac2db03f7a152a2cea8dbac4340a07f92609e86b1c3eac95d431620a

test:
  secret_key_base: 24f0e9d02defd0e4ae4717a28c0c6dd004139197646e6a02ec44ae47776097fb06df4652c2d33ddafdb4bdb4514f31cc9c3d28960e87a1c7b2cfc9b5e4d14e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
